#include "../firmware/CarReady/RoamPolicy.h"
#include "../firmware/CarReady/EchoPolicy.h"
constexpr float recovered[]={50,-1,51,52,50};
constexpr float latestMiss[]={50,51,50,52,-1};
constexpr float sparse[]={-1,-1,50,51,-1};
constexpr float uncertain[]={30,60,90,120,150};
constexpr float closeObstacle[]={60,61,62,60,10};
constexpr float highOutlier[]={60,61,62,60,280};
static_assert(stableEcho(recovered,5,4)==51,"Recover from one old miss using the supported cluster median");
static_assert(stableEcho(latestMiss,5,4)<0,"A current miss stops immediately");
static_assert(stableEcho(sparse,4,3)<0,"Two echoes are insufficient");
static_assert(stableEcho(uncertain,5,4)<0,"Scattered echoes must not enable movement");
static_assert(stableEcho(closeObstacle,5,4)==61,"One close outlier cannot poison a consistent far cluster");
static_assert(stableEcho(highOutlier,5,4)==61,"A far outlier must not inflate clearance");
// Decision regressions for measured clearance, escape progress and uncertainty.
static_assert(chooseRoam(28,60,31,0,0,true)==RoamChoice::FORWARD,"Open front should advance");
static_assert(chooseRoam(60,30,28,0,0,true)==RoamChoice::LEFT,"Measured left exit");
static_assert(chooseRoam(28,30,60,0,0,true)==RoamChoice::RIGHT,"Measured right exit");
static_assert(chooseRoam(35,30,25,0,0,true)==RoamChoice::ESCAPE_LEFT,"Dead end should pivot to inspect a new heading");
static_assert(chooseRoam(25,30,35,0,0,true)==RoamChoice::ESCAPE_RIGHT,"Opposite escape direction");
static_assert(chooseRoam(35,30,25,2,1,true)==RoamChoice::ESCAPE_RIGHT,"Retain escape direction instead of oscillating");
static_assert(chooseRoam(25,30,35,2,-1,true)==RoamChoice::ESCAPE_LEFT,"Retain left escape direction");
static_assert(chooseRoam(-1,30,35,0,0,true)==RoamChoice::ESCAPE_RIGHT,"Inspect new heading toward a measured side, without treating the unknown side as clear");
static_assert(chooseRoam(25,-1,35,0,0,true)==RoamChoice::SURVEY_RIGHT,"Missing center echo triggers inspection of another heading");
static_assert(chooseRoam(25,30,-1,0,0,true)==RoamChoice::ESCAPE_LEFT,"Measured left clearance permits bounded inspection");
static_assert(chooseRoam(-1,30,-1,0,0,true)==RoamChoice::SURVEY_RIGHT,"Unknown sides trigger bounded inspection instead of scan lock");
static_assert(chooseRoam(60,30,-1,0,0,true)==RoamChoice::LEFT,"Do not ignore a measured exit because the opposite sector missed");
static_assert(chooseRoam(15,30,60,0,0,true)==RoamChoice::TOO_CLOSE,"Known near corner still vetoes a turn");
#include "../firmware/CarReady/LinePolicy.h"
static_assert(lineSteering(0)==0 && lineSteering(2)==0 && lineSteering(5)==0,"Vendor straight patterns");
static_assert(lineSteering(1)>0 && lineSteering(3)>0,"Right corrections");
static_assert(lineSteering(4)<0 && lineSteering(6)<0,"Left corrections");
static_assert(lineSteering(7)==99,"All black or no floor stops");
static_assert(chooseRoam(17.9f,30,60,0,0,true)==RoamChoice::TOO_CLOSE,"Close corner blocks rotation even with an exit");
static_assert(chooseRoam(25,17.9f,35,0,0,true)==RoamChoice::TOO_CLOSE,"Too close in front");
static_assert(chooseRoam(18,28,18,0,0,true)==RoamChoice::ESCAPE_RIGHT,"Front and side pivot clearance boundaries");
static_assert(chooseRoam(35,30,25,7,-1,true)==RoamChoice::ESCAPE_LEFT,"Eighth turn allowed");
static_assert(chooseRoam(35,30,25,8,-1,true)==RoamChoice::EXHAUSTED,"No ninth turn");
static_assert(chooseRoam(60,30,25,8,-1,true)==RoamChoice::EXHAUSTED,"Bound failed clear-side turns too");
static_assert(chooseRoam(35,60,25,8,-1,true)==RoamChoice::FORWARD,"An actual forward exit ends the dead end");
static_assert(chooseRoam(35,30,25,0,0,false)==RoamChoice::EXHAUSTED,"Respect disabled escape option");
static_assert(chooseRoam(60,30,25,0,0,false)==RoamChoice::LEFT,"Normal measured exits remain available");
static_assert(chooseRoam(-1,-1,-1,0,0,true)==RoamChoice::SURVEY_RIGHT,"All missing echoes must not freeze the scan");
static_assert(chooseRoam(-1,-1,-1,2,-1,true)==RoamChoice::SURVEY_LEFT,"Keep inspecting the same direction toward the other side");
static_assert(chooseRoam(-1,-1,-1,8,1,true)==RoamChoice::EXHAUSTED,"Persistent missing echoes stop at the limit");
static_assert(chooseRoam(-1,-1,-1,0,0,false)==RoamChoice::UNKNOWN,"Disabled recovery never turns into unmeasured space");
static_assert(chooseRoam(10,-1,-1,0,0,true)==RoamChoice::TOO_CLOSE,"Known close echo vetoes unknown-heading inspection");
#include "../firmware/CarReady/RangePolicy.h"
constexpr float nearPair[]={60,61,62,11,10};
constexpr float falling[]={60,55,50,45,40};
static_assert(confirmedNearEcho(nearPair,5,4,35),"Two recent close echoes confirm a real obstacle");
static_assert(!confirmedNearEcho(closeObstacle,5,4,35),"Single spike is provisional, never a confirmed alert");
static_assert(stableEcho(nearPair,5,4)==10,"Two close echoes override three stale far readings immediately");
static_assert(stableEcho(falling,5,4)==40,"A coherent closing trend must not be hidden by older distances");
static_assert(chooseRoam(80,27,90,0,0,true)==RoamChoice::TOO_CLOSE,"Close front requires clearance recovery before a pivot");
static_assert(chooseRoam(60,54,40,0,0,true)==RoamChoice::LEFT,"Resume margin directs a route change rather than chatter");
static_assert(chooseRoam(60,55,40,0,0,true)==RoamChoice::FORWARD,"Resume at the hysteresis boundary");
static_assert(roamSpeed(65,25)==20 && roamSpeed(80,25)==25,"Approaching obstacles reduces roaming speed");
static_assert(retreatBudget(1000,5000,0,true)==350,"Bounded retreat can use recently traveled space");
static_assert(retreatBudget(0,0,0,true)==0,"No history means no blind reverse");
static_assert(retreatBudget(1000,8001,0,true)==0,"Stale trail cannot authorize reverse");
static_assert(retreatBudget(1000,100,2,true)==0,"At most two retreat attempts");
static_assert(retreatBudget(1000,100,0,false)==0,"Honor disabled backtracking");
static_assert(!warningDue(1100,1000,true,5000),"Repeated sensor warnings stay quiet");
static_assert(warningDue(6000,1000,true,5000),"Persistent faults may warn again after cooldown");
static_assert(warningDue(100,0,false,5000),"The first real warning is immediate");
